<a href="https://colab.research.google.com/github/aashikagarg/Neural-Network-/blob/main/Colab_link_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

K.R. MANGALAM UNIVERSITY

Assignment : Neural Network and Deep Learning

Name: Aashika Garg

Roll No: 2301201178

Class: BCA Sec-C

# PROJECT 2: STRUCTURED DATA
# PREPROCESSING & ANN Dataset: Titanic Survival (Tabular)

In [ ]:
import pandas as pd

# Upload Titanic CSV file
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [ ]:
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.drop(['Name','Ticket','Cabin','PassengerId'],axis=1,inplace=True)

df.head()

/tmp/ipykernel_10350/144245411.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_10350/144245411.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Convert categorical data
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['Embarked']=le.fit_transform(df['Embarked'])

# Features and target
X=df.drop('Survived',axis=1)
y=df['Survived']

# Scaling
sc=StandardScaler()
X=sc.fit_transform(X)

# Split data
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model=Sequential()

model.add(Dense(32,activation='relu',input_shape=(X_train.shape[1],)))
model.add(Dense(16,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(
optimizer='adam',
loss='binary_crossentropy',
metrics=['accuracy']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
history=model.fit(
X_train,
y_train,
epochs=50,
batch_size=16,
validation_split=0.2
)

Epoch 1/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.6573 - loss: 0.6465 - val_accuracy: 0.8042 - val_loss: 0.5842
Epoch 2/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7768 - loss: 0.5664 - val_accuracy: 0.8042 - val_loss: 0.5042
Epoch 3/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7891 - loss: 0.5027 - val_accuracy: 0.8252 - val_loss: 0.4422
Epoch 4/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7961 - loss: 0.4667 - val_accuracy: 0.8252 - val_loss: 0.4159
Epoch 5/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8049 - loss: 0.4527 - val_accuracy: 0.8182 - val_loss: 0.4020
Epoch 6/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8049 - loss: 0.4405 - val_accuracy: 0.8252 - val_loss: 0.4000
Epoch 7/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8172 - loss: 0.4334 - val_accuracy: 0.8252 - val_loss: 0.3997
Epoch 8/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8172 - loss: 0.4272 - val_accuracy: 0.8182 - val_loss: 0.3982
Epoch 9/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8155 - loss: 0.4214 - val_accuracy: 0.8182 - val_loss: 0.4000
Epoch 10/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.4182 - val_accuracy: 0.8392 - val_loss: 0.3925
Epoch 11/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8207 - loss: 0.4190 - val_accuracy: 0.8392 - val_loss: 0.3937
Epoch 12/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8243 - loss: 0.4108 - val_accuracy: 0.8322 - val_loss: 0.3944
Epoch 13/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8295 - loss: 0.4056 - val_accuracy: 0.8322 - val_loss: 0.3969
Epoch 14/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8295 - loss: 0.4037 - val_accuracy: 0.8392 - val_loss: 0.3902
Epoch 15/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8383 - loss: 0.3991 - val_accuracy: 0.8392 - val_loss: 0.3962
Epoch 16/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8330 - loss: 0.3972 - val_accuracy: 0.8322 - val_loss: 0.4011
Epoch 17/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8366 - loss: 0.3938 - val_accuracy: 0.8252 - val_loss: 0.3954
Epoch 18/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8330 - loss: 0.3924 - val_accuracy: 0.8252 - val_loss: 0.4040
Epoch 19/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8366 - loss: 0.3899 - val_accuracy: 0.8252 - val_loss: 0.3984
Epoch 20/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8401 - loss: 0.3874 - val_accuracy: 0.8252 - val_loss: 0.3967
Epoch 21/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8471 - loss: 0.3833 - val_accuracy: 0.8182 - val_loss: 0.4032
Epoch 22/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8401 - loss: 0.3830 - val_accuracy: 0.8252 - val_loss: 0.3986
Epoch 23/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8436 - loss: 0.3800 - val_accuracy: 0.8322 - val_loss: 0.3957
Epoch 24/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8453 - loss: 0.3778 - val_accuracy: 0.8182 - val_loss: 0.4045
Epoch 25/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8471 - loss: 0.3753 - val_accuracy: 0.8182 - val_loss: 0.3996
Epoch 26/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8436 - loss: 0.3747 - val_accuracy: 0.8182 - val_loss: 0.3998
Epoch 27/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8471 - loss: 0.3718 - val_accuracy: 0.8182 - val_loss: 0.4031
Epoch 28/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8489 - loss: 0.3725 - val_accuracy: 0.8112 - val_loss: 0.4028
Epoch 29/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8489 - loss: 0.3693 - val_accuracy: 0.8322 - val_loss: 0.4012
Epoch 30/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3691 - val_accuracy: 0.8112 - val_loss: 0.4050
Epoch 31/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8506 - loss: 0.3665 - val_accuracy: 0.8322 - val_loss: 0.3977
Epoch 32/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8524 - loss: 0.3697 - val_accuracy: 0.8252 - val_loss: 0.4057
Epoch 33/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8489 - loss: 0.3625 - val_accuracy: 0.8322 - val_loss: 0.4019
Epoch 34/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8559 - loss: 0.3620 - val_accuracy: 0.8322 - val_loss: 0.4022
Epoch 35/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8471 - loss: 0.3627 - val_accuracy: 0.8252 - val_loss: 0.4036
Epoch 36/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3624 - val_accuracy: 0.8322 - val_loss: 0.3978
Epoch 37/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8524 - loss: 0.3608 - val_accuracy: 0.8322 - val_loss: 0.4047
Epoch 38/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8524 - loss: 0.3570 - val_accuracy: 0.8322 - val_loss: 0.4034
Epoch 39/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8541 - loss: 0.3558 - val_accuracy: 0.8252 - val_loss: 0.4063
Epoch 40/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8506 - loss: 0.3562 - val_accuracy: 0.8322 - val_loss: 0.4081
Epoch 41/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8489 - loss: 0.3533 - val_accuracy: 0.8322 - val_loss: 0.4049
Epoch 42/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8541 - loss: 0.3529 - val_accuracy: 0.8182 - val_loss: 0.4085
Epoch 43/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8541 - loss: 0.3505 - val_accuracy: 0.8322 - val_loss: 0.4090
Epoch 44/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8559 - loss: 0.3509 - val_accuracy: 0.8322 - val_loss: 0.4091
Epoch 45/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8612 - loss: 0.3491 - val_accuracy: 0.8182 - val_loss: 0.4103
Epoch 46/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8541 - loss: 0.3492 - val_accuracy: 0.8182 - val_loss: 0.4162
Epoch 47/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8506 - loss: 0.3499 - val_accuracy: 0.8182 - val_loss: 0.4169
Epoch 48/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8576 - loss: 0.3489 - val_accuracy: 0.8182 - val_loss: 0.4185
Epoch 49/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8612 - loss: 0.3482 - val_accuracy: 0.8322 - val_loss: 0.4088
Epoch 50/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8629 - loss: 0.3463 - val_accuracy: 0.8252 - val_loss: 0.4136

In [ ]:
loss,accuracy=model.evaluate(X_test,y_test)

print("Accuracy =",accuracy)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8156 - loss: 0.4391
Accuracy = 0.8156424760818481

## PREPROCESSING & CNN Dataset: Cats vs Dogs (Unstructured Image Data)

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets,layers,models

# Load CIFAR-10 dataset automatically
(X_train,y_train),(X_test,y_test)=datasets.cifar10.load_data()

print("Training Images Shape:",X_train.shape)

# --------------------
# Preprocessing
# --------------------

# Normalize images
X_train = X_train / 255.0
X_test = X_test / 255.0

# --------------------
# CNN Model
# --------------------

model=models.Sequential()

model.add(layers.Conv2D(32,(3,3),
activation='relu',
input_shape=(32,32,3)))

model.add(layers.MaxPooling2D(2,2))

model.add(layers.Conv2D(64,(3,3),
activation='relu'))

model.add(layers.MaxPooling2D(2,2))

model.add(layers.Conv2D(64,(3,3),
activation='relu'))

model.add(layers.Flatten())

model.add(layers.Dense(64,
activation='relu'))

model.add(layers.Dense(10,
activation='softmax'))

# Compile model
model.compile(
optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy']
)

# Train model
model.fit(
X_train,
y_train,
epochs=5,
validation_data=(X_test,y_test)
)

# Evaluate
loss,accuracy=model.evaluate(X_test,y_test)

print("Accuracy =",accuracy)

Training Images Shape: (50000, 32, 32, 3)
Epoch 1/5
1455/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.3387 - loss: 1.7802